package dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bwie.myapplication.view.SouSuoSql.MySearBean;

import dao.MySearBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mySearBeanDaoConfig;

    private final MySearBeanDao mySearBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mySearBeanDaoConfig = daoConfigMap.get(MySearBeanDao.class).clone();
        mySearBeanDaoConfig.initIdentityScope(type);

        mySearBeanDao = new MySearBeanDao(mySearBeanDaoConfig, this);

        registerDao(MySearBean.class, mySearBeanDao);
    }
    
    public void clear() {
        mySearBeanDaoConfig.clearIdentityScope();
    }

    public MySearBeanDao getMySearBeanDao() {
        return mySearBeanDao;
    }

}
